apiVersion: apps.kubedl.io/v1alpha1
kind: Cron
metadata:
  name: cron-tf
  labels:
    app.kubernetes.io/name: cron-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  historyLimit: 3
  template:
    workload:
      apiVersion: kubeflow.org/v1
      kind: TFJob
      metadata:
        labels:
          key1: value1
          key2: value2
        annotations:
          key1: value1
          key2: value2
      spec:
        cleanPodPolicy: None
        tfReplicaSpecs:
          PS:
            replicas: 1
            restartPolicy: Never
            template:
              spec:
                containers:
                - name: tensorflow
                  image: kube-ai-registry.cn-shanghai.cr.aliyuncs.com/kube-ai/tensorflow-mnist-example:2.15.0-gpu
                  imagePullPolicy: IfNotPresent
                  command:
                  - /bin/bash
                  - -c
                  args:
                  - |
                    echo "PS: Start training..."
                    sleep 30
                    echo "PS: Training completed."
          Worker:
            replicas: 2
            restartPolicy: Never
            template:
              spec:
                containers:
                - name: tensorflow
                  image: kube-ai-registry.cn-shanghai.cr.aliyuncs.com/kube-ai/tensorflow-mnist-example:2.15.0-gpu
                  imagePullPolicy: IfNotPresent
                  command:
                  - /bin/bash
                  - -c
                  args:
                  - |
                    echo "Worker: Start training..."
                    sleep 30
                    echo "Worker: Training completed."
